CREATE TABLE [dbo].[HORARIOS] (
    [cve_turno]    NVARCHAR (1)   CONSTRAINT [DF_HORARIOS_cve_turno] DEFAULT ('') NOT NULL,
    [horario]      NVARCHAR (2)   CONSTRAINT [DF_HORARIOS_horario] DEFAULT ('') NOT NULL,
    [entra]        NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_entra] DEFAULT ((0)) NOT NULL,
    [sale]         NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_sale] DEFAULT ((0)) NOT NULL,
    [hora_turno]   NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_hora_turno] DEFAULT ((0)) NOT NULL,
    [hora_perio]   NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_hora_perio] DEFAULT ('') NOT NULL,
    [hrs_xturno]   NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_hrs_xturno] DEFAULT ((0)) NOT NULL,
    [hrs_apagar]   NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_hrs_apagar] DEFAULT ((0)) NOT NULL,
    [tolera_ent]   INT            CONSTRAINT [DF_HORARIOS_tolera_ent] DEFAULT ((0)) NOT NULL,
    [tolera_sal]   INT            CONSTRAINT [DF_HORARIOS_tolera_sal] DEFAULT ((0)) NOT NULL,
    [lunes]        NVARCHAR (10)  CONSTRAINT [DF_HORARIOS_lunes] DEFAULT ('') NOT NULL,
    [come_lun]     NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_come_lun] DEFAULT ('') NOT NULL,
    [horas_lun]    NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_horas_lun] DEFAULT ((0)) NOT NULL,
    [trans_lun]    NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_trans_lun] DEFAULT ((0)) NOT NULL,
    [martes]       NVARCHAR (10)  CONSTRAINT [DF_HORARIOS_martes] DEFAULT ('') NOT NULL,
    [come_mar]     NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_come_mar] DEFAULT ('') NOT NULL,
    [horas_mar]    NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_horas_mar] DEFAULT ((0)) NOT NULL,
    [trans_mar]    NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_trans_mar] DEFAULT ((0)) NOT NULL,
    [miercoles]    NVARCHAR (10)  CONSTRAINT [DF_HORARIOS_miercoles] DEFAULT ('') NOT NULL,
    [come_mie]     NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_come_mie] DEFAULT ('') NOT NULL,
    [horas_mie]    NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_horas_mie] DEFAULT ((0)) NOT NULL,
    [trans_mie]    NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_trans_mie] DEFAULT ((0)) NOT NULL,
    [jueves]       NVARCHAR (10)  CONSTRAINT [DF_HORARIOS_jueves] DEFAULT ('') NOT NULL,
    [come_jue]     NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_come_jue] DEFAULT ('') NOT NULL,
    [horas_jue]    NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_horas_jue] DEFAULT ((0)) NOT NULL,
    [trans_jue]    NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_trans_jue] DEFAULT ((0)) NOT NULL,
    [viernes]      NVARCHAR (10)  CONSTRAINT [DF_HORARIOS_viernes] DEFAULT ('') NOT NULL,
    [come_vie]     NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_come_vie] DEFAULT ('') NOT NULL,
    [horas_vie]    NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_horas_vie] DEFAULT ((0)) NOT NULL,
    [trans_vie]    NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_trans_vie] DEFAULT ((0)) NOT NULL,
    [sabado]       NVARCHAR (10)  CONSTRAINT [DF_HORARIOS_sabado] DEFAULT ('') NOT NULL,
    [come_sab]     NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_come_sab] DEFAULT ('') NOT NULL,
    [horas_sab]    NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_horas_sab] DEFAULT ((0)) NOT NULL,
    [trans_sab]    NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_trans_sab] DEFAULT ((0)) NOT NULL,
    [domingo]      NVARCHAR (10)  CONSTRAINT [DF_HORARIOS_domingo] DEFAULT ('') NOT NULL,
    [come_dom]     NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_come_dom] DEFAULT ('') NOT NULL,
    [horas_dom]    NUMERIC (4, 2) CONSTRAINT [DF_HORARIOS_horas_dom] DEFAULT ((0)) NOT NULL,
    [trans_dom]    NUMERIC (5, 2) CONSTRAINT [DF_HORARIOS_trans_dom] DEFAULT ((0)) NOT NULL,
    [carga_time]   INT            CONSTRAINT [DF_HORARIOS_carga_time] DEFAULT ((0)) NOT NULL,
    [descri]       NVARCHAR (140) CONSTRAINT [DF_HORARIOS_descri] DEFAULT ('') NOT NULL,
    [tipo_hor]     INT            CONSTRAINT [DF_HORARIOS_tipo_hor] DEFAULT ((0)) NOT NULL,
    [retard_men]   INT            CONSTRAINT [DF_HORARIOS_retard_men] DEFAULT ((0)) NOT NULL,
    [retard_may]   INT            CONSTRAINT [DF_HORARIOS_retard_may] DEFAULT ((0)) NOT NULL,
    [estado]       NVARCHAR (1)   CONSTRAINT [DF_HORARIOS_estado] DEFAULT ('') NOT NULL,
    [dias_asist]   NVARCHAR (25)  CONSTRAINT [DF_HORARIOS_dias_asist] DEFAULT ('') NOT NULL,
    [marca_dia]    INT            CONSTRAINT [DF_HORARIOS_marca_dia] DEFAULT ((0)) NOT NULL,
    [tipo_trans]   INT            CONSTRAINT [DF_HORARIOS_tipo_trans] DEFAULT ((0)) NOT NULL,
    [agre_tmpto]   NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_agre_tmpto] DEFAULT ('00:00') NOT NULL,
    [quit_tmpo]    NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_quit_tmpo] DEFAULT ('00:00') NOT NULL,
    [total_per]    INT            CONSTRAINT [DF_HORARIOS_total_per] DEFAULT ((0)) NOT NULL,
    [dias_lab]     INT            CONSTRAINT [DF_HORARIOS_dias_lab] DEFAULT ((0)) NOT NULL,
    [des_obl]      INT            CONSTRAINT [DF_HORARIOS_des_obl] DEFAULT ((0)) NOT NULL,
    [nombreTurno]  NVARCHAR (5)   CONSTRAINT [DF_HORARIOS_nombreTurno] DEFAULT ('') NOT NULL,
    [diasDescanso] NVARCHAR (20)  CONSTRAINT [DF_HORARIOS_diasDescanso] DEFAULT ('') NOT NULL
);

