CREATE TABLE [dbo].[TEXTRA] (
    [id_Textra]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [clave_emp]  NVARCHAR (5)   CONSTRAINT [DF__TEXTRA__clave_em__20C96AC7] DEFAULT ('') NOT NULL,
    [entra]      DATETIME2 (0)  CONSTRAINT [DF__TEXTRA__entra__21BD8F00] DEFAULT ('2050-12-31') NOT NULL,
    [sale]       DATETIME2 (0)  CONSTRAINT [DF__TEXTRA__sale__22B1B339] DEFAULT ('2050-12-31') NOT NULL,
    [horas]      NUMERIC (5, 2) CONSTRAINT [DF__TEXTRA__horas__23A5D772] DEFAULT ((0)) NOT NULL,
    [hor_dob]    NUMERIC (5, 2) CONSTRAINT [DF__TEXTRA__hor_dob__2499FBAB] DEFAULT ((0)) NOT NULL,
    [hor_tri]    NUMERIC (5, 2) CONSTRAINT [DF__TEXTRA__hor_tri__258E1FE4] DEFAULT ((0)) NOT NULL,
    [hrs_aut]    NUMERIC (5, 2) CONSTRAINT [DF__TEXTRA__hrs_aut__2682441D] DEFAULT ((0)) NOT NULL,
    [hrs_autd]   NUMERIC (5, 2) CONSTRAINT [DF__TEXTRA__hrs_autd__27766856] DEFAULT ((0)) NOT NULL,
    [hrs_autt]   NUMERIC (5, 2) CONSTRAINT [DF__TEXTRA__hrs_autt__286A8C8F] DEFAULT ((0)) NOT NULL,
    [semana]     INT            CONSTRAINT [DF__TEXTRA__semana__295EB0C8] DEFAULT ((0)) NOT NULL,
    [tipo_jorn]  NVARCHAR (1)   CONSTRAINT [DF__TEXTRA__tipo_jor__2A52D501] DEFAULT ('') NOT NULL,
    [depto]      NVARCHAR (6)   CONSTRAINT [DF__TEXTRA__depto__2B46F93A] DEFAULT ('') NOT NULL,
    [cont_div]   NVARCHAR (6)   CONSTRAINT [DF__TEXTRA__cont_div__2C3B1D73] DEFAULT ('') NOT NULL,
    [superv]     NVARCHAR (5)   CONSTRAINT [DF__TEXTRA__superv__2D2F41AC] DEFAULT ('') NOT NULL,
    [depto_orig] NVARCHAR (6)   CONSTRAINT [DF__TEXTRA__depto_or__2E2365E5] DEFAULT ('') NOT NULL,
    [div_orig]   NVARCHAR (6)   CONSTRAINT [DF__TEXTRA__div_orig__2F178A1E] DEFAULT ('') NOT NULL,
    [superv_ori] NVARCHAR (5)   CONSTRAINT [DF__TEXTRA__superv_o__300BAE57] DEFAULT ('') NOT NULL,
    [estado]     INT            CONSTRAINT [DF__TEXTRA__estado__30FFD290] DEFAULT ((0)) NOT NULL,
    [acepta]     INT            CONSTRAINT [DF__TEXTRA__acepta__31F3F6C9] DEFAULT ((0)) NOT NULL,
    [tipo_cargo] INT            CONSTRAINT [DF__TEXTRA__tipo_car__32E81B02] DEFAULT ((0)) NOT NULL,
    [sup_gene]   NVARCHAR (5)   CONSTRAINT [DF__TEXTRA__sup_gene__33DC3F3B] DEFAULT ('') NOT NULL,
    [taxi]       INT            CONSTRAINT [DF__TEXTRA__taxi__34D06374] DEFAULT ((0)) NOT NULL,
    [taxi_para]  INT            CONSTRAINT [DF__TEXTRA__taxi_par__35C487AD] DEFAULT ((0)) NOT NULL,
    [hor_taxi1]  NVARCHAR (5)   CONSTRAINT [DF__TEXTRA__hor_taxi__36B8ABE6] DEFAULT ('') NOT NULL,
    [dir_taxi1]  NVARCHAR (70)  CONSTRAINT [DF__TEXTRA__dir_taxi__37ACD01F] DEFAULT ('') NOT NULL,
    [hor_taxi2]  NVARCHAR (5)   CONSTRAINT [DF__TEXTRA__hor_taxi__38A0F458] DEFAULT ('') NOT NULL,
    [dir_taxi2]  NVARCHAR (70)  CONSTRAINT [DF__TEXTRA__dir_taxi__39951891] DEFAULT ('') NOT NULL,
    [comedor]    INT            CONSTRAINT [DF__TEXTRA__comedor__3A893CCA] DEFAULT ((0)) NOT NULL,
    [desa]       BIT            CONSTRAINT [DF__TEXTRA__desa__3B7D6103] DEFAULT ((0)) NOT NULL,
    [come]       BIT            CONSTRAINT [DF__TEXTRA__come__3C71853C] DEFAULT ((0)) NOT NULL,
    [meri]       BIT            CONSTRAINT [DF__TEXTRA__meri__3D65A975] DEFAULT ((0)) NOT NULL,
    [cena]       BIT            CONSTRAINT [DF__TEXTRA__cena__3E59CDAE] DEFAULT ((0)) NOT NULL,
    [observa]    VARCHAR (MAX)  CONSTRAINT [DF__TEXTRA__observa__3F4DF1E7] DEFAULT ('') NOT NULL,
    [alta]       DATETIME2 (0)  CONSTRAINT [DF__TEXTRA__alta__40421620] DEFAULT ('2050-12-31') NOT NULL,
    [modifica]   DATETIME2 (0)  CONSTRAINT [DF__TEXTRA__modifica__41363A59] DEFAULT ('2050-12-31') NOT NULL,
    [imp_doble]  NUMERIC (6, 2) CONSTRAINT [DF__TEXTRA__imp_dobl__422A5E92] DEFAULT ((0)) NOT NULL,
    [imp_triple] NUMERIC (6, 2) CONSTRAINT [DF__TEXTRA__imp_trip__431E82CB] DEFAULT ((0)) NOT NULL,
    [i_taxi_ent] NUMERIC (7, 2) CONSTRAINT [DF__TEXTRA__i_taxi_e__4412A704] DEFAULT ((0)) NOT NULL,
    [i_taxi_sal] NUMERIC (7, 2) CONSTRAINT [DF__TEXTRA__i_taxi_s__4506CB3D] DEFAULT ((0)) NOT NULL,
    [clave_cole] NVARCHAR (4)   CONSTRAINT [DF__TEXTRA__clave_co__45FAEF76] DEFAULT ('') NOT NULL,
    [clave_cols] NVARCHAR (4)   CONSTRAINT [DF__TEXTRA__clave_co__46EF13AF] DEFAULT ('') NOT NULL,
    [cve_secte]  INT            CONSTRAINT [DF__TEXTRA__cve_sect__47E337E8] DEFAULT ((0)) NOT NULL,
    [cve_sects]  INT            CONSTRAINT [DF__TEXTRA__cve_sect__48D75C21] DEFAULT ((0)) NOT NULL,
    [ruta]       INT            CONSTRAINT [DF__TEXTRA__ruta__49CB805A] DEFAULT ((0)) NOT NULL,
    [utilizado]  NVARCHAR (1)   CONSTRAINT [DF__TEXTRA__utilizad__4ABFA493] DEFAULT ('') NOT NULL,
    [valido]     INT            CONSTRAINT [DF__TEXTRA__valido__4BB3C8CC] DEFAULT ((0)) NOT NULL,
    [a_fiscal]   INT            CONSTRAINT [DF__TEXTRA__a_fiscal__4CA7ED05] DEFAULT ((0)) NOT NULL,
    [folio]      INT            CONSTRAINT [DF__TEXTRA__folio__4D9C113E] DEFAULT ((0)) NOT NULL,
    [autorizado] BIT            CONSTRAINT [DF__TEXTRA__autoriza__4E903577] DEFAULT ((0)) NOT NULL,
    [sel]        BIT            CONSTRAINT [DF__TEXTRA__sel__4F8459B0] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TEXTRA] PRIMARY KEY CLUSTERED ([id_Textra] ASC)
);

